players:
  TheBoykissOld:
    ip: "192.168.1.1"
    discord_id: "123456789012345678"
whitelist:
  - "TheBoykissOld"
discord:
  token: "tu token de bot de Discord"
  channel_id: "el ID de tu canal de Discord"